//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaTelefonica.DAO.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cliente_telefone
    {
        public int Id { get; set; }
        public string Descricao { get; set; }
        public string Numero { get; set; }
        public int IdCliente { get; set; }
    
        public virtual tbl_cliente tbl_cliente { get; set; }
    }
}
